package sec02.exam02;

public class TrycatchFinallyRuntimeExceptionExample {
	public static void main(String[] args) {
		String data1 = null;
		String data2 = null;
		try {
			data1 = args[0];
			data2 = args[1];
		} catch (ArrayIndexOutOfBoundsException e) { 
			System.out.println("실행 매개값의 수가 부족합니다.");
			return;
		}
	
		
		try {
			int value1 = Integer.parseInt(data1);
			int value2 = Integer.parseInt(data2);
			int result = value1 + value2;
			
			
		} catch (Exception e) {
			// TODO: handle exception
		}
}

}
